CREATE DATABASE IF NOT EXISTS Company;
USE Company;

CREATE TABLE IF NOT EXISTS employees(
id INT NOT NULL AUTO_INCREMENT,
Name VARCHAR(60),
Email VARCHAR(50),
Position VARCHAR(15),
PRIMARY KEY(id)
);